### ISSUE TITLE
`json_schema` argument required during installation could be optional

### ISSUE THREAD

**Issue by davidatwhiletrue** [casper-ecosystem/enhanced-nft#148]
The runtime argument `json_schema` should only be required during installation when the metadata kind is `CustomValidated`. For other kinds, it should be optional (or even ignored).

**Comment by hoffmannjan** [comment]
+1, found the same today :)

**Comment by cryofracture** [comment]
I have also duplicated this issue when installing with `raw` metadataKind modality.
