### ISSUE TITLE
Can't remove operator for a single token.

### ISSUE THREAD

**Issue by zie1ony** [casper-ecosystem/enhanced-nft#155]
Correct me if I'm wrong, but `approve` method doesn't allow to remove the operator.

**Comment by gRoussac** [comment]
Correct me if wrong an operator can not approve another <s>operator</s> account.

**Comment by gRoussac** [comment]
Hi @zie1ony thanks for your report. I am closing this issue in favor of https://github.com/casper-ecosystem/cep-78-enhanced-nft/issues/174
