### ISSUE TITLE
Split `transfer` into `transfer` and `transfer_from`.

### ISSUE THREAD

**Issue by zie1ony** [casper-ecosystem/enhanced-nft#158]
Currently `transfer` handles both: normal transfers and transfers from operators. It could be split into `transfer` and `transfer_from`, same way ERC721 works. It would make code simpler and cheaper.

**Comment by RitaMAllenCA** [comment]
@EdHastingsCasperLabs is this a breaking change?

**Comment by piotr-dziubecki** [comment]
breaking change?

**Comment by piotr-dziubecki** [comment]
introduce transfer_from as opposed to get split

**Comment by gRoussac** [comment]
Hi all, @zie1ony 

Thanks for your report, afaik there is no transfer method in ERC721, it's however the name of an event. It has a `transferFrom` method that behaves like current `transfer` entry point. 

If I am adding the guess that this would require for a non breaking API to keep `transfer` as it is and add a `transferFrom` that would have the same code (an owner can still transfer his token using the new `transferFrom`)

I took this reference of the ERC https://docs.openzeppelin.com/contracts/3.x/api/token/erc721#IERC721

Please let me know if I miss something here.

**Comment by zie1ony** [comment]
@gRoussac you are right. Closing.

**Comment by gRoussac** [comment]
thanks
