### ISSUE TITLE
Code duplicates.

### ISSUE THREAD

**Issue by zie1ony** [casper-ecosystem/enhanced-nft#159]
I see a lot of duplicates in both `contracts` and `tests`. I think the codebase could be 1/3 of its current size. I suggest adding one more layer of abstraction. That would make code shorter and more readable.

**Comment by gRoussac** [comment]
@zie1ony Error excepted I believe you already kindly de-duplicate this code into https://github.com/casper-ecosystem/cep-78-enhanced-nft/commit/c93c68be4ef7de580c102f321a83ba08dc3c6f9b 

Is there any more duplication between contract and tests you wanted me to address or can we close this issue for now while feat-cesp branch gets merged ? thanks

**Comment by gRoussac** [comment]
@gRoussac check constants files

**Comment by gRoussac** [comment]
I am de-duplicating some constants into https://github.com/casper-ecosystem/cep-78-enhanced-nft/pull/181/commits/bbf885aa2b45b5e62dd4db91f974f20388800494
