### ISSUE TITLE
Review of testing code added for the make PR 

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-ecosystem/enhanced-nft#160]
The initial round of reviews pointed out the lack of tests included.  The PR has been updated with the added tests and now we must review them as well.

**Comment by gRoussac** [comment]
@RitaMAllenCA @darthsiroftardis 

- I believe last changes are very good, relevant tests were added for several entry points, now it's more clear what to expect from these events.
- I think the refactoring mutualizing structs for tests and lib is right thing to do
- I believe the PR fixes a previous test on this line which is a good catch. 
https://github.com/casper-ecosystem/cep-78-enhanced-nft/pull/150/files#diff-448ccf02a24ab3cb56fb149a628795ea3d448bc8ce3bcd8a49b9f1aad460dfe6R831

- I am still not a big fan of [src/events.rs](https://github.com/casper-ecosystem/cep-78-enhanced-nft/pull/150/files#diff-e6b367605eb370c608fd74585147b016fc1e3b7fbd190772df677f70c77a3302), on code point of view there seems to be some duplication declining events. I would have made a generic struct that gets a type of event. But I don't see a reason to reject current code for that.

- Branch is still out of date compare to base branch, not sure if this makes a big diff right now

For the rest I have no particular opinion on how the data is serialized for the key/value.
