### ISSUE TITLE
Merge Make PR and CEP-47 to feature Branch

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-ecosystem/enhanced-nft#163]

**Comment by RitaMAllenCA** [comment]
asked MAKE to unblock the PR. 2.17.23

**Comment by gRoussac** [comment]
Hi @RitaMAllenCA @darthsiroftardis I believe this ticket should have been closed by merged https://github.com/casper-ecosystem/cep-78-enhanced-nft/pull/164 

However I don't know when this branch is planned to be merged to dev branch.
