### ISSUE TITLE
`set_approval_for_all` fails if the caller owns a burnt token

### ISSUE THREAD

**Issue by davidatwhiletrue** [casper-ecosystem/enhanced-nft#166]
STR:
 - mint two tokens
 - burn the first minted token
 - call `set_approval_for_all` to add an operator

ER:
 - the call succeeds, and the operator can manage the second token.

AR:
 - the call fails with the error `User error: 42`, which means `PreviouslyBurntToken`.

This happens because when a token is burnt it's not removed from the owners dictionary (or page). The error is thrown here:

https://github.com/casper-ecosystem/cep-78-enhanced-nft/blob/568dd06707841906b13317d750d9b98cf9c41994/contract/src/main.rs#L846

This issue is related also with https://github.com/casper-ecosystem/cep-78-enhanced-nft/issues/145

**Comment by davidatwhiletrue** [comment]
There's a test to check that this method fails if there're burnt tokens. Why is `set_approval_for_all` not allowed in this situation?

https://github.com/casper-ecosystem/cep-78-enhanced-nft/blob/568dd06707841906b13317d750d9b98cf9c41994/tests/src/burn.rs#L572

**Comment by darthsiroftardis** [comment]
Closed by #164 and #172
