### ISSUE TITLE
`set_approval_for_all` fails if `NFTIdentifierMode` is `Hash`

### ISSUE THREAD

**Issue by davidatwhiletrue** [casper-ecosystem/enhanced-nft#167]
STR:
 - install the contract with `NTFIdentifierMode::Hash` and `OwnerReverseLookupMode.NoLookup`.
 - mint two tokens
 - call `set_approval_for_all` to add an operator

ER:
 - the call succeeds, and the operator can manage the tokens

AR:
 - the call fails with the error `User error: 28`, which means `InvalidTokenIdentifier`.

This happens because a bug here:

https://github.com/casper-ecosystem/cep-78-enhanced-nft/blob/568dd06707841906b13317d750d9b98cf9c41994/contract/src/utils.rs#L650

The loop should stop at `current_number_of_minted_tokens -1`.

**Comment by darthsiroftardis** [comment]
Closed by #164 and #172
