### ISSUE TITLE
`set_approval_for_all` does not behave as expected

### ISSUE THREAD

**Issue by ihor** [casper-ecosystem/enhanced-nft#172]
The current implementation of the `set_approval_for_all` method in the reference CEP-78 NFT standard implementation does not behave as expected. Ideally, this method should allow for the approval of multiple operators, enabling token owners to list their tokens on multiple marketplaces. However, this is not currently possible with the CEP-78 standard, limiting it to exclusive listings.

The method only approves tokens owned at the time of the entry point call, and does not cover tokens acquired later. This is because it simply loops over all of the owner's tokens and approves them individually, making the operation very expensive in terms of gas usage. In fact, a warning in the [comment next to the entry point](https://github.com/casper-ecosystem/cep-78-enhanced-nft/blob/568dd06707841906b13317d750d9b98cf9c41994/contract/src/main.rs#L801) advises developers to "DO NOT invoke this entrypoint unless absolutely necessary."

This unexpected behavior may also confuse dApp developers who are familiar with Ethereum's ERC-721 standard, potentially hurting the adoption of the Casper network.

To address these issues, we recommend changing the `set_approval_for_all` implementation in the following ways:

1. The entry point should allow owners to approve operators to manage all of their tokens in the contract, rather than individual tokens owned at the time of execution.
2. The entry point should make it possible to allow approval of multiple operators.
3. The entry point should have a corresponding getter method called `is_approved_for_all`, which returns whether an operator is approved to manage all tokens owned by an owner.

**Comment by ihor** [comment]
Addressing this issue will fix the following issues as well:
- #167 
- #166 
- #145

**Comment by RitaMAllenCA** [comment]
adding dependencies to connect the issues - They are RELATED, not DEPENDENT, but this is the best Github/Zenhub allows.

**Comment by ihor** [comment]
Linking the testing ticket #176

**Comment by ihor** [comment]
@darthsiroftardis please note that the `ApprovalForAll` event should drop the `token_ids` field after the change.
