### ISSUE TITLE
Add ability to revoke approval permissions to CEP-78

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-ecosystem/enhanced-nft#174]
Since we allow assignment of approval permissions, we need to provide the ability to revoke it as well.

**Comment by RitaMAllenCA** [comment]
@darthsiroftardis @gRoussac Please estimate asap

**Comment by gRoussac** [comment]
https://github.com/casper-ecosystem/cep-78-enhanced-nft/issues/155
