### ISSUE TITLE
Extend testing on set_approval_for_all 

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-ecosystem/enhanced-nft#176]
Set_approval_for_all updates permissions of the "assignee" to include 'approval' permission.  We need to test that once the permission is updated, it will also allow the "assignee" to assign 'approval' permissions to node operators.  Similarly, it should allow revocation of approval.

**Comment by RitaMAllenCA** [comment]
@gRoussac @darthsiroftardis please provide an estimate by Tuesday 2.28

**Comment by ihor** [comment]
This ticket has potentially confusing wording. To have parity with ERC-721, approved operators should have possibility to approve an address, but not other operators.

ERC-721 provide confusing terminology with terms sounds similar from the natural language perspective, but having different domain meanings. The standard separates “approval for all”, which can be applied to multiple operators from single “approve”, which can be applied only to a single address.

```
| Permission type  | Object name      | Supports multiple Object |
|------------------|------------------|--------------------------|
| Approve          | Approved address | No                       |
| Approval for all | Operator         | Yes                      | 
```
which have the following permissions
```
| Caller           | Can call "approve" | Can call "set_approval_for_all" |
|------------------|--------------------|---------------------------------|
| Owner            | Yes                | Yes                             |
| Operator         | Yes                | No                              |
| Approved address | No                 | No                              |
```
The above was derived from [ERC-721](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/caba6b93ef14ee95fe35a76e5c7929e574fe298e/contracts/token/ERC721/ERC721.sol#L346) and [ERC-1155](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/caba6b93ef14ee95fe35a76e5c7929e574fe298e/contracts/token/ERC1155/ERC1155.sol#L369) implementations.
Additionally please look at the screenshot from the [ERC-721 standard description](https://eips.ethereum.org/EIPS/eip-721).
