### ISSUE TITLE
Add Repo License

### ISSUE THREAD

**Issue by gskerry** [casper-ecosystem/enhanced-nft#19]

**Comment by piotr-dziubecki** [comment]
follow the same model as for casper-node.

**Comment by gskerry** [comment]
@piotr-dziubecki @EdHastingsCasperLabs 
OK. So will add Apache license (c) 2022 Casper Association ([as for casper-node](https://github.com/casper-network/casper-node/blob/dev/LICENSE))

...[CEP-47](https://github.com/casper-ecosystem/casper-nft-cep47/blob/master/LICENSE) was MIT (c) 2021 Casper "Ecosystem"
