### ISSUE TITLE
Can't read from owned_tokens dictionary anymore

### ISSUE THREAD

**Issue by jonas089** [casper-ecosystem/enhanced-nft#198]
I successfully minted an NFT using this command:
```
  casper-client put-deploy \
  --node-address http://195.201.167.179:7777/ \
  --chain-name casper-test \
  --secret-key ./secret_key.pem \
  --payment-amount 100000000000 \
  --session-hash b1d96ea7536bf6c9a2f65484ad75651f9a86ed72ba9897593054a0dc847f08de \
  --session-entry-point mint \
  --session-arg "token_owner:key='account-hash-32e24c2eb139804ad8db550dd79d78c370559069c137519a48b048bd77ca7da4'" \
  --session-arg "token_meta_data:string='{\"nft_name\":\"somename03\",\"nft_description\":\"somedescription01\",\"nft_url\":\"someurl01\"}'"
```
where contract-b1d96ea7536bf6c9a2f65484ad75651f9a86ed72ba9897593054a0dc847f08de is my Cep78 contract: 
https://testnet.cspr.live/contract-package/c8ef8d01c8f6933dd4dc4d542ec132b21a31622f190889a33b982f8653a4f16c

and then tried to query the owned_tokens dictionary:

```
casper-client get-dictionary-item \
  -n http://195.201.167.179:7777/ \
  -s e8fb65709de52240b972579af8c9ccd667c8845e8c307849b9dc0d6a7185b5e6 \
  --contract-hash  contract-b1d96ea7536bf6c9a2f65484ad75651f9a86ed72ba9897593054a0dc847f08de \
  --dictionary-name owned_tokens \
  --dictionary-item-key 32e24c2eb139804ad8db550dd79d78c370559069c137519a48b048bd77ca7da4
```
  
but i'm getting this error: **Failed to parse the dictionary identifier**

I also tried:
```
casper-client get-dictionary-item \
  -n http://195.201.167.179:7777/ \
  -s e8fb65709de52240b972579af8c9ccd667c8845e8c307849b9dc0d6a7185b5e6 \
  --account-hash  account-hash-b1d96ea7536bf6c9a2f65484ad75651f9a86ed72ba9897593054a0dc847f08de \
  --dictionary-name owned_tokens \
  --dictionary-item-key 32e24c2eb139804ad8db550dd79d78c370559069c137519a48b048bd77ca7da4
```
where i get this error: 
**{
  "code": -32003,
  "message": "state query failed: ValueNotFound(\"Failed to find base key at path: Key::Account(b1d96ea7536bf6c9a2f65484ad75651f9a86ed72ba9897593054a0dc847f08de)\")"
}**

**Comment by RitaMAllenCA** [comment]
@ipopescu @ACStoneCL any chance either of you can take a look and advise Jonas from the association?  Concerned this may be an issue with minting - can we rule that out?

**Comment by EdHastingsCasperAssociation** [comment]
casper-client get-dictionary-item \
  -n `<node ip>` \
  -s `<state root hash>` \
  --contract-hash hash-`<your contract hash>` \
  --dictionary-name **hash_by_index** \
  --dictionary-item-key `<ordinal here>`
  
  take the parsed value from the response, such as `2dadbef3f61d9427bac063a8133a6f044461951e688de3a682b601e29263632f`, and then pass that value as the dictionary-item-key as so:
  
  casper-client get-dictionary-item \
  -n `<node ip>` \
  -s `<state root hash>` \
   --contract-hash hash-`<your contract hash>` \
  --dictionary-name **token_issuers** \
  --dictionary-item-key `<token hash / parsed value from above command goes here>`
  
  -------------------------
note contract hash prefix is `hash-` as below

  ![image](https://user-images.githubusercontent.com/49160758/227050740-9339d46e-1b02-44a4-8c52-19a371eee690.png)

**Comment by jonas089** [comment]
I also tried this with the Javascript SDK:
```javascript
const {CLPublicKey, CLAccountHash, CLValueBuilder, Contracts, CasperClient, DeployUtil} = require('casper-js-sdk');

let publickey = "01daad67ebbcb725e02a1955a6617512b311435a21ca6d523085aa015d2d1b473a"

function toHexString(byteArray) {
    return Array.from(byteArray, function(byte) {
    return ('0' + (byte & 0xFF).toString(16)).slice(-2);
    }).join('')
}

function fromPublic(publickey){
  let accHash = CLPublicKey.fromHex(publickey).toAccountHash();
  let accHashHex = toHexString(accHash);
  return accHashHex;
}

async function call(){
  let account_hash = fromPublic(publickey);
  let peer = "http://195.201.167.179:7777/rpc/";
  let cep78_contract_hash = "hash-b1d96ea7536bf6c9a2f65484ad75651f9a86ed72ba9897593054a0dc847f08de";
  let owned = [];

  const data = {
    "account_hash": account_hash,
    "peer": peer
  }

  const client = await new CasperClient(peer);
  var cep78_contract_instance = new Contracts.Contract(client);
  cep78_contract_instance.setContractHash(cep78_contract_hash);

  return new Promise((resolve, reject) => {
    cep78_contract_instance.queryContractDictionary(
      "owned_tokens", // hardcoded as part of NFT standard.
      account_hash
    )
    .then(response => {
      for (let i = 0; i < response.data.length; i++){
        owned.push(response.data[i].data);
      };
      resolve(owned);
    })
    .catch(error => {
      const e = "Failed to find base key at path"
      if (error.toString().includes(e.toString())) {
        console.log("Account does not own any tokens");
        resolve([]);
      }
      else{
        console.log("Connection Error.");
        writeLog(`[E1]->${error}`);
        reject(error);
      }
    });
  });
}

async function main() {
  try {
    const owned = await call();
    console.log(owned);
  } catch (error) {
    console.log(error);
  }
}

main();
```

The same error was thrown ( **failed to parse base key at path** ). The error usually implies that the account does not own any NFTs, however I do have a valid mint for the account where token_owner is set to the account:
https://testnet.cspr.live/deploy/116621ee2c6b48e29a1a64aab8dd73e22dc2a3b6f037f61a21bc15afe21662cf

**Comment by EdHastingsCasperAssociation** [comment]
look at the example i provided. alternately i can jump on a zoom w/ you if you like.

**Comment by jonas089** [comment]
> casper-client get-dictionary-item -n `<node ip>` -s `<state root hash>` --contract-hash hash-`<your contract hash>` --dictionary-name **hash_by_index** --dictionary-item-key `<ordinal here>`
> 
> take the parsed value from the response, such as `2dadbef3f61d9427bac063a8133a6f044461951e688de3a682b601e29263632f`, and then pass that value as the dictionary-item-key as so:
> 
> casper-client get-dictionary-item -n `<node ip>` -s `<state root hash>` --contract-hash hash-`<your contract hash>` --dictionary-name **token_issuers** --dictionary-item-key `<token hash / parsed value from above command goes here>`
> 
> note contract hash prefix is `hash-` as below
> 
> ![image](https://user-images.githubusercontent.com/49160758/227050740-9339d46e-1b02-44a4-8c52-19a371eee690.png)

I have tried this as well and got the same error. I see you are querying a different dictionary. Is the owned_tokens dictionary deprecated?

**Comment by jonas089** [comment]
What if I want a list of all my owned NFTs? This used to be in the owned_tokens but what you are recommending is retrieving a single NFT's hash by ordinal ID? Isn't it possible anymore to query a list of all hashes for all owned NFTs?

**Comment by ipopescu** [comment]
We have a tutorial [here](https://github.com/casper-ecosystem/cep-78-enhanced-nft/blob/dev/tutorials/token-ownership-tutorial.md). Jonas, have you tried it?

**Comment by EdHastingsCasperAssociation** [comment]
![image](https://user-images.githubusercontent.com/49160758/227051640-59a5e467-8ed3-4c0c-977e-63e6bf15c5d4.png)

looks like token_owners works also

**Comment by jonas089** [comment]
Yes, but I am looking for owned_tokens, not token_owners.

**Comment by EdHastingsCasperAssociation** [comment]
i didn't write and don't maintain this contract, I'm just glancing at the `mint` method and reading what it says.

**Comment by jonas089** [comment]
I have an extract from an old tutorial that I made for a prior version of Cep78, where I was able to query owned_tokens as such:
$ casper-client get-dictionary-item \
-n http://136.243.187.84:7777/ \
-s 256d0445121f1144a09394c739c9baf82b5624b66dced181a0c1c8b8e936652b \
--account-hash hash-b4b78992e0324be09f174637c3dda2d29cc5c21c44430b72a0943d3ba6d2c827 \
--dictionary-name owned_tokens \
--dictionary-item-key 5a54f173e71d3c219940dcb9dfec222b024cd81aa7e0672de59ba5fab296448b

but this method and the variations of it that I have mentioned above does not work anymore ( it used to ). So that's why I've opened this issue. I will try to reach the dict via uref next, but I expect the same result for "owned_tokens". I see that the code has been changed and therefore I think it might be that it was deprecated or broken during development. I will run more tests but the javascript SDK example above should also work based off past experiences. However, something seems to have changed.

**Comment by EdHastingsCasperAssociation** [comment]
The original owned list of 1.0 was replaced by a pagination model in 1.1 iirc. At this point I'll let the cep-78 experts take over, but the line of play I cobbled together for you seems to work on the code as is to me so perhaps that helps you in the meantime until tomorrow when Karan and the gang are back online.

**Comment by jonas089** [comment]
I found the uref of the owned_tokens dictionary. This implies that it has not been deprecated? Not 100% sure but I will leave this test as another resource to help Karan and the Cep78 team:
`            "key": "uref-136996cef78acab1286a80abcd7b21c0cde4cd0bc6b79a7aaf26e017f01f4482-007",
            "name": "owned_tokens"
          },
 `
It looks like my account-hash is **not** a key in this dictionary, which is odd.
It should be possible to query this dictionary for my account-hash.
When I perform the query for the uref as per the tutorial:
`jonass-macbook-air:Desktop chef$ casper-client get-dictionary-item --node-address http://195.201.167.179:7777 --state-root-hash 7ec4d4ff5cb095b79eeaff4506c1d7def5924bc4fbc0cb379d4335610efa7f5d --seed-uref "uref-136996cef78acab1286a80abcd7b21c0cde4cd0bc6b79a7aaf26e017f01f4482-007" --dictionary-item-key 32e24c2eb139804ad8db550dd79d78c370559069c137519a48b048bd77ca7da4
`
I get the same error:
{
  "code": -32003,
  "message": "state query failed: ValueNotFound(\"Failed to find base key at path: Key::Dictionary(456d0a64cc640977de0ae8fe8f999c55c551a7d47f8311dc3dd600f5dcb5666f)\")"
}

After trying to query the dictionary with the casper-client and the javascript SDK and always getting the same error " Failed to parse base key " my conclusion is that for some reason my account-hash is not a key in the owned_tokens dictionary, even though I have minted an NFT for my account. 
I have tried multiple times and am very sure at this point that there is an issue with the owned_tokens dict, or a recent change that I am unaware of, so I'll wait for the team to take a look at it.

**Comment by jonas089** [comment]
It is really about this "owned_tokens" dict in particular. It's not a general issue with parsing dictionaries.

**Comment by EdHastingsCasperAssociation** [comment]
glancing at the diff between release-1.0.0 & release-1.1.0 it does look like that usage of the "OWNED_TOKENS" dictionary was replaced by the pagination logic... you can CTRL+F thru the diff to quickly see the change points:

https://github.com/casper-ecosystem/cep-78-enhanced-nft/compare/release-1.0.0..release-1.1.0

There's various touch points, but this snippet for example is typical of the swap out of the original impl for a new paged impl:

![image](https://user-images.githubusercontent.com/49160758/227056382-be8fbd3b-0130-489c-a6ca-da1206def2a3.png)

**Comment by jonas089** [comment]
But then why is the owned_tokens dictionary still created? And how could I perform a query for all token-hashes owned by my account?

**Comment by jonas089** [comment]
```
// Returns the length of the Vec<String> in OWNED_TOKENS dictionary. If key is not found
// it returns 0.
#[no_mangle]
pub extern "C" fn balance_of() {
    let owner_key = utils::get_named_arg_with_user_errors::<Key>(
        ARG_TOKEN_OWNER,
        NFTCoreError::MissingAccountHash,
        NFTCoreError::InvalidAccountHash,
    )
    .unwrap_or_revert();

    let owner_key_item_string = utils::encode_dictionary_item_key(owner_key);

    let balance = utils::get_dictionary_value_from_key::<u64>(TOKEN_COUNT, &owner_key_item_string)
        .unwrap_or(0u64);

    let balance_cl_value =
        CLValue::from_t(balance).unwrap_or_revert_with(NFTCoreError::FailedToConvertToCLValue);
    runtime::ret(balance_cl_value);
}

```

This function in the latest cep78 also implies that the owned_tokens dict is still in use

**Comment by jonas089** [comment]
OLD:       
```rust
owned_tokens.push(token_identifier.clone());
            match identifier_mode {
                NFTIdentifierMode::Ordinal => {
                    let token_indices: Vec<u64> = owned_tokens
                        .into_iter()
                        .map(|identifier| identifier.get_index().unwrap_or_revert())
                        .collect();
                    utils::upsert_dictionary_value_from_key(
                        OWNED_TOKENS,
                        &owned_tokens_item_key,
                        token_indices,
                    )
                }
                NFTIdentifierMode::Hash => {
                    let token_hashes: Vec<String> = owned_tokens
                        .into_iter()
                        .map(|identifier| identifier.get_hash().unwrap_or_revert())
                        .collect();
                    utils::upsert_dictionary_value_from_key(
                        OWNED_TOKENS,
                        &owned_tokens_item_key,
                        token_hashes,
                    )
                }
            }
```
            
 NEW:
```rust
         match identifier {
            NFTIdentifierMode::Ordinal => utils::migrate_owned_tokens_in_ordinal_mode(),
            NFTIdentifierMode::Hash => {
                storage::new_dictionary(HASH_BY_INDEX)
                    .unwrap_or_revert_with(NFTCoreError::FailedToCreateDictionary);
                storage::new_dictionary(INDEX_BY_HASH)
                    .unwrap_or_revert_with(NFTCoreError::FailedToCreateDictionary);
                runtime::put_key(
                    UNMATCHED_HASH_COUNT,
                    storage::new_uref(current_number_of_minted_tokens).into(),
                );
            }
        }
    }
```

I see... now all I'd need to know to successfully query the new dictionaries is, how I can get the amount of tokens owned by the account. Then I should be able to query for the HASH_BY_INDEX.

**Comment by jonas089** [comment]
I think I just answered my own question... My last 2 answers combined might do the trick. Will try.

**Comment by jonas089** [comment]
YES! - Here we go :)

```
jonass-macbook-air:~ chef$   casper-client get-dictionary-item   -n http://195.201.167.179:7777   -s 5b4ee57f886e10bbf766cfaa6b2b8b1d9c14212fde67562ca3905d187879ecbb   --contract-hash hash-b1d96ea7536bf6c9a2f65484ad75651f9a86ed72ba9897593054a0dc847f08de   --dictionary-name balances   --dictionary-item-key 32e24c2eb139804ad8db550dd79d78c370559069c137519a48b048bd77ca7da4
{
  "id": -2754351506409120321,
  "jsonrpc": "2.0",
  "result": {
    "api_version": "1.4.13",
    "dictionary_key": "dictionary-5f76d3255e4fd3b935abc77ab988c84ac1fc49acbad284116191fcd3a18590fb",
    "merkle_proof": "[38456 hex chars]",
    "stored_value": {
      "CLValue": {
        "bytes": "0300000000000000",
        "cl_type": "U64",
        "parsed": 3
      }
    }
  }
}
```

**Comment by jonas089** [comment]
Not quite tho, it looks like the HASH_BY_INDEX dictionary is per contract, not per account. Therefore we still don't know which tokens we own and it is still odd that the owned_tokens dict exists but can't be queried.

**Comment by jonas089** [comment]
I'm sorry for all the messages, I've worked through this real-time. 
Closing note for the day:
The issue persists and there seems to be no way of retrieving all hashes of the NFTs owned by an account. These should be in the owned_tokens dictionary which appears to be empty after mint.

**Comment by RitaMAllenCA** [comment]
We will have more people take a look tomorrow, have a good night

**Comment by darthsiroftardis** [comment]
@jonas089 as part of the 1.1 version of CEP-78, we deprecated the `owned_dictionary` dictionary which tracked a list of token hashes or ids. We did this because tracking ownership in this manner would cause mints and transfers to have ever increasing gas costs as these lists grew in size. Since the release of 1.1 we have moved to more gas efficient paging based model to track ownership, and introducing a new modality that tracks tokens owned by a given `Account` or `Contract`. However, that modality is an optional argument and reverse tracking is turned off by default. Please have a look at the tutorials which should help you track NFTs you own: https://github.com/casper-ecosystem/cep-78-enhanced-nft/tree/dev/tutorials

**Comment by jonas089** [comment]
It's more complex that the old version, but I think I can make sense of it.

**Comment by jonas089** [comment]
Should the owned_tokens dict be removed from the code?

**Comment by darthsiroftardis** [comment]
> Should the owned_tokens dict be removed from the code?

Yes, its a bug that we still create that dictionary
