### ISSUE TITLE
CEP-78 v1.2.0 README example command has backtick

### ISSUE THREAD

**Issue by cryofracture** [casper-ecosystem/enhanced-nft#203]
**Describe the issue**
Casper client commands without comments aren't easily copy/pastable, one command had an errant backtick (`).

1. Navigate to [CEP-78 README Minting Section](https://github.com/casper-ecosystem/cep-78-enhanced-nft/tree/v1.2.0#minting-an-nft) 
2. Click to expand "casper client command without comments"

**Expected behavior**
Code block is not copy/pastable 

**Defect Type**
- [ ] Regression
- [x] New
- [ ] Escape

**Comment by RitaMAllenCA** [comment]
HI @ACStoneCL  - what is needed to get this merged?
Taylor does't appear to be a user (???) but I also pinged him in slack

**Comment by ACStone-MTS** [comment]
If @cryofracture doesn't have the necessary access/authorization, I can merge it - @gRoussac approved the PR.
