### ISSUE TITLE
merge 1.3 back to dev 

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-ecosystem/enhanced-nft#229]
we have to be sure we merge 1.3 AND feature -1.4 to dev before we release.

**Comment by RitaMAllenCA** [comment]
I am not sure if this has been done, so writing a ticket to ensure it has been.  Please connect the PR and close the ticket if this is complete @gRoussac

**Comment by gRoussac** [comment]
@RitaMAllenCA according to my test there is right now no difference between branch release-1.3.0 and dev branch. @darthsiroftardis please let me know if I miss anything here. Closing thanks
