### ISSUE TITLE
Produce a design specification for `cep-78`

### ISSUE THREAD

**Issue by devendran-m** [casper-ecosystem/enhanced-nft#23]
Objective - Solution Architect(s) to produce a design specification for the implementation of `cep-78`

Definition of Done - Create a design specification that can be referred and used by developers and other teams to build their NFT solution using the cep-78 standard.

**Comment by Gamal-A** [comment]
Document updated on the below link:
https://docs.google.com/document/d/1mhnvaVN7627syDvAAIo5-OJ9eEbC8RPio8tJnNsC5ZI/edit?usp=sharing

**Comment by devendran-m** [comment]
Closing based on the update from @Gamal-A and the attached document.
