### ISSUE TITLE
casper-cep78-js-client package

### ISSUE THREAD

**Issue by jdaly13** [casper-ecosystem/enhanced-nft#230]
I recently installed this package from npm and using it in a node module but when you try to import package I get an error
`Please verify that the package.json has a valid "main" entry`
when I look in the package.json the main entry is   
`"main": "dist/index.js",`
when it should be 
`"main": "dist/src/index.js",`

As there are no files in the dist directory just two sub directories src and wasm

**Comment by RitaMAllenCA** [comment]
@hoffmannjan please respond, thanks

**Comment by RitaMAllenCA** [comment]
checking in - we are looking at this and will respond soon.

**Comment by hoffmannjan** [comment]
yeah you're right - there will be a bugfix release! thanks for this @jdaly13 !
