### ISSUE TITLE
allow operators to burn the nft

### ISSUE THREAD

**Issue by imsk17** [casper-ecosystem/enhanced-nft#243]
The burn endpoint simply does not care about approval as of right now. but, the operator should be allowed to burn the nft. IE in both ERC721 and ERC1155 contracts, an operator can burn the token

**Comment by RitaMAllenCA** [comment]
@gRoussac @zoltan @EdHastingsCasperLabs please comment so we can respond.   @RBYGLLS

**Comment by imsk17** [comment]
I would like to work on this one if possible.

**Comment by gRoussac** [comment]
Hi all, @imsk17 thanks for raising this issue.

The ercs are not very specific on that, I guess it depends of the implementation of the interface but it does not seem an hard requirement tho.
![ERC-721-OpenZeppelin-Docs (1)](https://github.com/casper-ecosystem/cep-78-enhanced-nft/assets/3099551/3a454b18-1a91-4e82-9827-8123586ad4b9)
![ERC-1155-OpenZeppelin-Docs](https://github.com/casper-ecosystem/cep-78-enhanced-nft/assets/3099551/ef0e5d6b-e29b-4e89-a4ce-13526ad1d54f)



I think the decision was taken to only allow an owner to burn its token in ceps 18/78/85. I believe this should remain default case but could be a modality in cep-78 and 85 (allow operator burn). It could be also a "modality" in form of a boolean on install of cep-18 probably. I would recommend to do the three ceps alike and at the same time + corresponding tests in each.

**Comment by imsk17** [comment]
so, should I implement this modality on all three standards?

**Comment by zoltan** [comment]
you might want to put the right person there, as I'm the wrong @zoltan :)

**Comment by gRoussac** [comment]
@deuszex FYI

**Comment by gRoussac** [comment]
@imsk17 thanks for your report and kind proposition, we needed to treat a previous related issue #249 on mint/transfers before this operator burn mode. I opened a PR #250 to add it on CEP-78 for now.
