### ISSUE TITLE
CEP47 => CEP78

### ISSUE THREAD

**Issue by devendran-m** [casper-ecosystem/enhanced-nft#25]
Objective - The objective of this epic is to analyse, and create example code and scripts for teams to migrate from `cep-47-nft` to `cep-78-enhanced-nft`. 

Following are the related tickets created and will be tracked as part of this epic.
Note - There are two possible migration strategies that require a detailed feasibility study as part of this epic/plan.
1. Vanilla `cep-47-nft` to Vanilla(Enhanced) `cep-78-enhanced-nft` migration
2. Custom `cep-47-nft` to Enhanced `cep-78-enhanced-nft`

- [x] #26
- [x] #27

**Comment by Ehsan4490** [comment]
4 months have passed and this issue is still not solved?
When is the update for Cep_78

**Comment by RitaMAllenCA** [comment]
won't do
