### ISSUE TITLE
SRE Testing: CEP78 Minting - ApiError::EarlyEndOfStream [17]

### ISSUE THREAD

**Issue by RBYGLLS** [casper-ecosystem/enhanced-nft#277]
Observation:
Assuming the recent condor-rc3 commit was supposed to get cep working

successful installation of contract

minting with mint_call wasm V2

put-transaction session through Lane 3 - Large
execution_error: "ApiError::EarlyEndOfStream [17]"
"execution_result": {
"Version2": {
"initiator": {
"PublicKey": "010f4e780413b30a973bc2c6181959695af55edc6e5eebe7bbc11bb0148c335b80"
},
"error_message": "ApiError::EarlyEndOfStream [17]",
"limit": "100000000000",
"consumed": "411881110",
"cost": "100000000000",
"payment": [],
"transfers": [],
"size_estimate": 36772,
"effects": [

**Comment by deuszex** [comment]
Disclaimer:

It was not supposed to get cep-78 in working order.

No PR has been raised to suggest so, nor was there any announcement regarding that.
