### ISSUE TITLE
contract always appears in account `namedKeys` as `nft_contract_*`

### ISSUE THREAD

**Issue by hoffmannjan** [casper-ecosystem/enhanced-nft#41]
so it can cause overwriting previously installed contract on the same account.
maybe it's a good idea to use `collection_name` as a part of named key?

**Comment by RitaMAllenCA** [comment]
@darthsiroftardis need an estimate

**Comment by RitaMAllenCA** [comment]
We have changed the internal model, making this issue no longer relevant.
