### ISSUE TITLE
Multiple Metadata (Contract Modality) 

### ISSUE THREAD

**Issue by gskerry** [casper-ecosystem/enhanced-nft#57]
Provide contract compatibility for multiple, simultaneous consumers - via a modality for multiple metadata schemas at once (for the same contract).

i.e. extension of [nftmetadatakind](https://github.com/casper-ecosystem/cep-78-enhanced-nft#nftmetadatakind) to support multiple schemas.

TBD:
Configuration settings around Required, Optional, Default.

**Comment by gRoussac** [comment]
@RBYGLLS @deuszex Error excepted this has already been treated ?

https://github.com/casper-ecosystem/cep-78-enhanced-nft/pull/78

**Comment by deuszex** [comment]
Correct @gRoussac this should be one of the issues that we discussed on multiple meetings that it is done. But be sure to wait on management to declare it so.

**Comment by RBYGLLS** [comment]
Closing this EPIC as the work has been deemed completed in the following ticket:
https://app.zenhub.com/workspaces/cep78-62f310b4981d7b002374a745/issues/gh/casper-ecosystem/cep-78-enhanced-nft/123
