### ISSUE TITLE
CEP-78 Event Emitter (Contract)

### ISSUE THREAD

**Issue by gskerry** [casper-ecosystem/enhanced-nft#58]

**Comment by RitaMAllenCA** [comment]
@darthsiroftardis what do you think about closing this issue since CEP-78 moved away from contract events?  It may be better to either repurpose this ticket or create a new one when we determine the priority of convenience SDK updates.

**Comment by Ehsan4490** [comment]
Hello
When Cep-78  v1. 1 Complete?

**Comment by RitaMAllenCA** [comment]
> Hello When Cep-78 v1. 1 Complete?

It was released on Dec 21, 2022

**Comment by RitaMAllenCA** [comment]
reopened only for bookkeeping of PRs.....  closing again
