### ISSUE TITLE
Multiple Metadata (Contract Modality)

### ISSUE THREAD

**Issue by gskerry** [casper-ecosystem/enhanced-nft#60]
Provide contract compatibility for multiple, simultaneous consumers - via a modality for multiple metadata schemas at once (for the same contract).

i.e. extension of [nftmetadatakind](https://github.com/casper-ecosystem/cep-78-enhanced-nft#nftmetadatakind) to support multiple schemas.

TBD:
Configuration settings around Required, Optional, Default.

**Comment by deuszex** [comment]
https://github.com/casper-ecosystem/cep-78-enhanced-nft/pull/78

**Comment by RitaMAllenCA** [comment]
@deuszex we are going to close this ticket to get the credit for the work.  PR will be closed and another reopened so that we can combine this work with the refactoring work Karan may want to do in CEP-78. Stay tuned
