### ISSUE TITLE
Whitelisting Support 

### ISSUE THREAD

**Issue by gskerry** [casper-ecosystem/enhanced-nft#62]
Update the CEP 78 contract: Create a new modality for minting called "limited".  This can be used to support whitelisting capabilities in either the contract or account.

**Comment by RitaMAllenCA** [comment]
current whitelist is for contracts.  Would like to do the same thing for accounts, which is currently not supported.

**Comment by gRoussac** [comment]
FYI, the whitelist can't be combined for several reasons, mostly keeping Accounts the main NFTHolder mode and being retro compatible on upgrade from previous version.

**Comment by RitaMAllenCA** [comment]
can we do this via multisig? Need to discuss.  Multi sig is global - for the entire account; not specific to cep-78.   May need to resolve with a proxy account, which would serve as a whitelist.

**Comment by gRoussac** [comment]
@RitaMAllenCA The open  PR is working though and is tested. But Ryo submitted the idea of switching to dictionaries both lists, Zoltan likes the idea and I was wondering if Karan would let it be into dictionaries as per comment on the PR https://github.com/casper-ecosystem/cep-78-enhanced-nft/pull/162#issuecomment-1473783748 for next version.

For the multisig part, I am not sure what is meant like that but if Karan wants to explain a proxy we can have a look.
