### ISSUE TITLE
Should token issuer be the token minter?

### ISSUE THREAD

**Issue by davidatwhiletrue** [casper-ecosystem/enhanced-nft#64]
The dictionary token_issuers stores the first owner of a token. But, the name suggests to me that it's storing the minter of that token. Is it correct?

https://github.com/casper-ecosystem/cep-78-enhanced-nft/blob/bc40dc82d8a7e7fd9d5aac668fd110cf4dc919c6/contract/src/main.rs#L490

**Comment by jonas089** [comment]
Token issuer can be the token minter, but doesn't have to be. I think you can mint to another address.

**Comment by davidatwhiletrue** [comment]
Thanks @jonas089 for your answer.
Then, semantically, issuer != minter, right?

**Comment by gRoussac** [comment]
Hi @davidatwhiletrue, thanks for your report. As discussed please have a look at this PR and let me know if this fixes correctly the issue.

https://github.com/casper-ecosystem/cep-78-enhanced-nft/pull/170

thanks
