### ISSUE TITLE
init() entry point lacks 2 parameters. Only 14/16 are defined => error when calling metadata() and other.

### ISSUE THREAD

**Issue by jonas089** [casper-ecosystem/enhanced-nft#65]
When calling the metadata() function an error is raised that says the NFT_METADATA_KIND is not set.
METADATA_MUTABILITY is also not found in storage.
I think I have identified the reason for this issue and will try to resolve it.
The attached screenshots show that the 2 missing parameters are passed to the init() function, but are not defined as parameters for the init() entry point => this explains why they are not set.
I test my fix tomorrow and propose a commit.

![1662415712953](https://user-images.githubusercontent.com/49498646/188727310-6794be74-54bc-4932-b44f-906b330c9938.jpeg)
![1662415694775](https://user-images.githubusercontent.com/49498646/188727313-a48edaf6-5ad2-4b93-b1c3-fcf33fa02a3b.jpeg)

**Comment by gRoussac** [comment]
Hi @jonas089 thanks for your report. 

I believe this has been fixed meanwhile in this commit https://github.com/casper-ecosystem/cep-78-enhanced-nft/commit/f5c93830e75320935ce17b0f5384017191a32396#diff-bb08d6927664d81e3bb0c97846211dc11b8ccd735a98fea518b59ffe397adae7R1396

from this PR https://github.com/casper-ecosystem/cep-78-enhanced-nft/pull/87 adding the missing parameters in init entry point.

Those tests are covering that logic https://github.com/casper-ecosystem/cep-78-enhanced-nft/blob/dev/tests/src/metadata.rs#L222-L364 if you find anything left that I may have missed then please let me know back thanks.
