### ISSUE TITLE
Support for Royalty Processing

### ISSUE THREAD

**Issue by gskerry** [casper-ecosystem/enhanced-nft#77]
https://docs.google.com/document/d/1e7xus87EzHFJ51VqEJeyk9Sfsoo5gOsunW88qFT90RI/edit?usp=meetingnotes&showmeetingnotespromo=true

**Comment by gRoussac** [comment]
https://github.com/ElusiveMori/ceps/blob/trading/text/0082-cep-78-trading-extension.md
