### ISSUE TITLE
Update CI/CD to publish npm package

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-ecosystem/enhanced-nft#80]
To support the updated SDK for CEP-78, we need to include npm - possibly other libraries.  Please work with the engineers to ensure the pipeline is updated to include all dependencies.

**Comment by RitaMAllenCA** [comment]
@bradjohnl @hoffmannjan please work together during the week of 10.24 to determine requirements and get an estimate.  SRE team works on L1 cycles, so Luca's focus should be to finish his work for the L1 milestone. 
Working on a plan to improve this staggered sprint process and help out SRE....

**Comment by bradjohnl** [comment]
@RitaMAllenCA I see, but I am already fully scheduled for the L2 sprint, so in theory I have no bandwidth to work on additional issues also on the L1 sprint if that is what you meant, unless something is deprioritized and this assignment can find its place.
If the meaning is that I should take all my work to the L1 sprint cycle, do you mean to put all of my tickets, that are now on L2, on the L1 sprint beginning on Monday and add the estimating work with @hoffmannjan on top?

**Comment by bradjohnl** [comment]
@hoffmannjan I think the best thing to do is to have a call so that you can explain to me in detail what is required? This would also render the estimation possible on my side.

**Comment by hoffmannjan** [comment]
@RitaMAllenCA - sorted it out with @bradjohnl. I can modify the gh-actions scripts from [casper-js-sdk repo](https://github.com/casper-ecosystem/casper-js-sdk) - that won't be a lot of hassle for me - and then we can test it together with Luca.
